name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install, prepare
        run: |
          npm install
          npm run prepare
      - run: npm run npm-publish
        env:
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_PASS: ${{ secrets.NPM_PASS }}
