name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "The release version in <MAJOR>.<MINOR>.<PATCH> format"
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: "Check release version"
        run: |
          expr "${{ github.event.inputs.releaseVersion }}" : '\(^[1-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\(-beta\.[1-9][0-9]*\)\{0,1\}\)$'

      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.QAMETA_CI }}

      - name: "Configure CI Git User"
        run: |
          git config --global user.name qameta-ci
          git config --global user.email qameta-ci@qameta.io

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: "Prepare"
        run: |
          npm ci
          npm run prepare

      - name: "Set release version"
        run: |
          npm run set-version '${{ github.event.inputs.releaseVersion }}'

      - name: "Publish Github Release"
        uses: toolmantim/release-drafter@v5.15.0
        with:
          tag: v${{ github.event.inputs.releaseVersion }}
          publish: "true"
          version: ${{ github.event.inputs.releaseVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.QAMETA_CI }}
